project:
  type: website
  output-dir: docs
website: 
  title: "PPEC0039 - Introdução ao Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Sobre
      - href: atividade_disciplina.qmd
        text: PPEC0039

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2